baseurl = "https://rodriguekayembe.com/"  # please update this to your actual URL
languageCode = "en-gb"
title = "Rodrigue Kayembe"
theme = "personal-site-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
note = "/note/:year/:month/:day/:slug/"
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[[menu.main]]
name = "Categories"
url = "categories/"
weight = 3

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 4

[[menu.main]]
name = "Subscribe"
url = "index.xml"

[params]
description = "Virtual home on the internet"
footer = "&copy; [Rodrigue Kayembe](https://rodriguekayembe.com) {Year} | [Github](https://github.com/rodriguekayembe) |"

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters = { block = [["\\[", "\\]"], ["$$", "$$"]], inline = [["\\(", "\\)"]] }